### ISSUE TITLE
Mammography use-case?

### ISSUE THREAD

**Issue by jamesjjcondon** [gkaissis/PriMIA#53]
Hi,

I'd like to explore using PriMIA for mammography, which is a perfect use-case for your platform. I'm happy to work on a PR for an appropriate dataset, dataloader and model. But I couldn't see anything in the dependencies for loading images or dicoms, how does PriMIA address this? And I assume you want to avoid adding dependencies?

Is this something you would be interested in?

Thanks and great work. Very exciting.

James.

**Comment by jamesjjcondon** [comment]
Never mind re the first few questions. Found it [here](https://github.com/gkaissis/PriMIA/blob/master/torchlib/dicomtools.py) and thanks for your [video](https://www.youtube.com/watch?v=eTwR8GpNK34) . Let me have a bit more of a look around, it might work out of the box for mammograms!

**Comment by gkaissis** [comment]
Closing as this seems addressed 😄
