### ISSUE TITLE
Documentation web site does not work

### ISSUE THREAD

**Issue by khoaguin** [gkaissis/PriMIA#56]
Hi, I try to go to the url https://gkaissis.github.io/PriMIA/, but it does not work. The error is `404 - There isn't a GitHub Pages site here.`

**Comment by gkaissis** [comment]
We apologise, there is a problem with google fonts so we had to take the documentation down temporarily. You can find the source in the gh-pages branch if you want to read the documentation.

**Comment by khoaguin** [comment]
Thank you
